const test = require('node:test'), assert = require('node:assert/strict'), crypto = require('node:crypto');
test('F038 authenticated body records, preview, concurrency, target application and ownership', { skip: process.env.ASTITVA_TEST_BODY_GOALS !== '1', timeout: 60000 }, async t => {
  const uri = process.env.F038_TEST_MONGODB_URL;
  if (!/^mongodb:\/\/127\.0\.0\.1:27138\/f038_fixture_[a-z0-9_]+\?replicaSet=f038test$/.test(uri || '')) throw Error('Disposable F038 fixture required.');
  Object.assign(process.env, { ASTITVA_ENV: 'dev', MONGODB_URL: 'mongodb://127.0.0.1:27017/astitva', PLAID_ENABLED: 'false', PLAID_ENV: 'sandbox', PLAID_CLIENT_ID: 'fixture', PLAID_SECRET: 'fixture', FINANCE_TOKEN_ENCRYPTION_KEY: '11'.repeat(32) });
  const m = require('mongoose'); await m.connect(uri);
  t.after(async () => { await m.connection.dropDatabase(); await m.disconnect(); });
  const User = require('../src/models/User'), Session = require('../src/models/Session'), Flags = require('../src/models/InvitedEmail');
  const Body = require('../src/models/BodyGoals'), { Targets } = require('../src/models/Diet');
  await Promise.all([Body.init(), Targets.init()]);
  const users = await User.create(['Owner', 'Other', 'Disabled', 'WeightOnly'].map(name => ({ name, email: `f038-${name.toLowerCase()}@example.invalid`, passwordHash: 'fixture', emailVerifiedAt: new Date() })));
  await Flags.create(users.map((u, i) => ({ email: u.email, diet: i !== 2, family: true })));
  const tokens = users.map(() => crypto.randomBytes(32).toString('hex'));
  await Session.create(users.map((u, i) => ({ userId: u._id, tokenHash: crypto.createHash('sha256').update(tokens[i]).digest('hex'), expiresAt: new Date(Date.now() + 3600000) })));
  const server = require('../src/app').createApp().listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const api = async (method, path = '', body, actor = 0, extra = {}) => {
    const r = await fetch(`http://127.0.0.1:${server.address().port}/api/diet/body-goals${path}`, { method, headers: { Origin: 'http://localhost:3000', 'Content-Type': 'application/json', ...(actor === null ? {} : { Authorization: `Bearer ${tokens[actor]}` }), ...extra }, body: body ? JSON.stringify(body) : undefined });
    return { status: r.status, body: await r.json() };
  };
  const date = new Date().toISOString().slice(0, 10);
  const input = { heightCm: 180, weightKg: 80, measuredOn: date, units: 'metric', age: 35, sex: 'male', activity: 'sedentary', eligible: true, goal: 'lose', targetWeightKg: 75, planMode: 'pace', paceKgWeek: 0.25, targetDate: null, expectedRevision: 0 };
  assert.equal((await api('GET', '', null, null)).status, 401);
  assert.equal((await api('GET', '', null, 2)).status, 403);
  assert.equal((await api('POST', '/preview', input)).status, 200);
  assert.equal(await Body.countDocuments(), 0);
  assert.equal((await api('PUT', '', { ...input, weightKg: '80' })).status, 400);
  let r = await api('PUT', '', input); assert.equal(r.status, 200, JSON.stringify(r.body));
  assert.equal(r.body.profile.revision, 1); assert.equal(r.body.profile.weights.length, 1);
  assert.equal((await api('GET')).body.profile.weightKg, 80);
  assert.equal((await api('GET', '', null, 1)).body.profile, null);
  assert.equal((await api('PUT', '', input)).status, 409);
  assert.equal((await api('POST', '/apply-target', { expectedRevision: 1 })).status, 409);
  await Targets.create({ userId: users[0]._id, calories: 1940, proteinGrams: 100, carbohydrateGrams: 250, fatGrams: 60, fiberGrams: 25, waterMilliliters: 2000 });
  r = await api('POST', '/apply-target', { expectedRevision: 1 }); assert.equal(r.status, 200, JSON.stringify(r.body));
  assert.equal(r.body.profile.revision, 2);
  let targets = await Targets.findOne({ userId: users[0]._id });
  assert.equal(targets.calories, r.body.appliedCalories); assert.equal(targets.waterMilliliters, 2000); assert.equal(targets.fiberGrams, 25);
  assert.equal(await Targets.countDocuments({ userId: users[1]._id }), 0);
  assert.equal((await api('POST', '/apply-target', { expectedRevision: 1 })).status, 409);
  r = await api('PUT', '', { ...input, weightKg: 79, expectedRevision: 2 }); assert.equal(r.status, 200);
  assert.equal(r.body.profile.weights.length, 1); assert.equal(r.body.profile.weights[0].weightKg, 79);
  assert.equal(r.body.profile.baseline.weightKg, 80);
  r = await api('PUT', '', { ...input, age: 17, expectedRevision: 3 }); assert.equal(r.status, 200);
  assert.equal((await api('POST', '/apply-target', { expectedRevision: 4 })).status, 400);
  const past = new Date(Date.parse(date + 'T00:00:00Z') - 86400000).toISOString().slice(0,10);
  const weightPath = '/weights/' + date;
  r = await api('PUT', weightPath, { weightKg: 70, units: 'metric', expectedRevision: 0 }, 3);
  assert.equal(r.status, 200, JSON.stringify(r.body)); assert.equal(r.body.profile, null); assert.equal(r.body.revision, 1); assert.equal(r.body.latestWeight.weightKg, 70);
  assert.equal((await api('GET', weightPath, null, 3)).body.entry.weightKg, 70);
  assert.equal((await api('PUT', weightPath, { weightKg: 69, units: 'metric', expectedRevision: 0 }, 3)).status, 409);
  assert.equal((await api('PUT', weightPath, { weightKg: '69', units: 'metric', expectedRevision: 1 }, 3)).status, 400);
  r = await api('PUT', '/weights/' + past, { weightKg: 71, units: 'metric', expectedRevision: 1 }, 3);
  assert.equal(r.status, 200); assert.equal(r.body.latestWeight.weightKg, 70); assert.equal(r.body.weights.length, 2);
  r = await api('PUT', weightPath, { weightKg: 69, units: 'metric', expectedRevision: 2 }, 3);
  assert.equal(r.status, 200); assert.equal(r.body.weights.length, 2); assert.equal(r.body.latestWeight.weightKg, 69);
  assert.equal((await api('POST', '/apply-target', {expectedRevision:3}, 3)).status, 400);
  r = await api('PUT', '', { ...input, weightKg: 69, targetWeightKg:65, age:null, sex:null, activity:null, expectedRevision:3 }, 3);
  assert.equal(r.status, 200, JSON.stringify(r.body)); assert.equal(r.body.profile.heightCm, 180); assert.equal(r.body.weights.length, 2); assert.ok(r.body.estimate.prediction); assert.equal(r.body.estimate.proposedCalories, null);
  const unchanged = (await Targets.findOne({userId:users[0]._id})).calories;
  r = await api('PUT', weightPath, {weightKg:75,units:'metric',expectedRevision:4}); assert.equal(r.status, 200);
  r = await api('PUT', '', {...input, weightKg:75,expectedRevision:5}); assert.equal(r.status,200,JSON.stringify(r.body)); assert.equal(r.body.estimate.goalReached,true);
  assert.equal((await Targets.findOne({userId:users[0]._id})).calories, unchanged);
  // Managed records follow authorized ownership and migrate on claiming.
  const { Person, Unit, Membership } = require('../src/models/FamilyUnit');
  const person = await Person.create({ name: 'Managed adult' });
  const actorPerson = await Person.create({ name: users[0].name, userId: users[0]._id });
  const unit = await Unit.create({ creatorId: users[0]._id, anchors: [{ personId: actorPerson._id, relationship: 'self' }] });
  await Membership.create([{ unitId: unit._id, personId: actorPerson._id, role: 'ADMIN' }, { unitId: unit._id, personId: person._id }]);
  const managed = { 'X-Astitva-Member': String(person._id), 'X-Astitva-Family': String(unit._id) };
  r = await api('PUT', '', input, 0, managed); assert.equal(r.status, 200, JSON.stringify(r.body));
  assert.equal(await Body.countDocuments({ userId: person._id }), 1);
  assert.ok([403, 404].includes((await api('GET', '', null, 1, managed)).status));
  const S = require('../src/services/managedWorkspace');
  assert.equal(await S.hasData(person._id), true);
  await m.connection.transaction(async session => S.transfer(person._id, users[1]._id, session));
  assert.equal(await Body.countDocuments({ userId: person._id }), 0);
  assert.equal((await api('GET', '', null, 1)).body.profile.weightKg, 80);
});
