const test = require('node:test'), assert = require('node:assert/strict'), crypto = require('node:crypto');
test('F041 OAuth PKCE, tools, own-data scope, refresh rotation and revocation', { skip: process.env.ASTITVA_TEST_MCP !== '1', timeout: 60000 }, async t => {
 const mongoose = require('mongoose');
 await mongoose.connect('mongodb://127.0.0.1:27141/f041_fixture_' + process.pid);
 t.after(async()=>{await mongoose.connection.dropDatabase();await mongoose.disconnect()});
 const express = require('express'), cookieParser = require('cookie-parser');
 const {installMcp} = require('../src/routes/mcp');
 const {unsafeOriginGuard} = require('../src/middleware/security');
 const {Grant,Client,Authorization,Bucket} = require('../src/models/Mcp');
 const User=require('../src/models/User'),Session=require('../src/models/Session'),Flags=require('../src/models/InvitedEmail');
 const {Meal,Targets,WaterEntry,LibraryMeal}=require('../src/models/Diet'),{Library,Reference}=require('../src/models/MealLibrary');
 await Promise.all([Grant,Client,Authorization,Bucket,Library,Reference,Targets,LibraryMeal].map(model=>model.init()));
 const users=await User.create(['owner','other','unverified'].map((name,i)=>({name,email:name+'@example.invalid',passwordHash:'fixture',emailVerifiedAt:i===2?null:new Date()})));
 await Flags.create(users.map(u=>({email:u.email,diet:true,mcp:true})));
 const tokens=users.map(()=>crypto.randomBytes(32).toString('hex')); const hash=require('../src/services/mcpAuth').hash;
 await Session.create(users.map((u,i)=>({userId:u._id,tokenHash:hash(tokens[i]),expiresAt:new Date(Date.now()+3600000)})));
 Object.assign(process.env,{ASTITVA_ENV:'dev',MONGODB_URL:'mongodb://127.0.0.1:27017/astitva',PLAID_ENV:'sandbox',PLAID_CLIENT_ID:'fixture',PLAID_SECRET:'fixture',FINANCE_TOKEN_ENCRYPTION_KEY:'11'.repeat(32)});
 const app=express();app.use(cookieParser());
 const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));
 const base='http://127.0.0.1:'+server.address().port,resource=base+'/mcp';
 const runtime={isProduction:true,webUrl:'http://localhost:3000',corsOrigins:['http://localhost:3000'],mcpPublicUrl:resource};app.locals.runtime=runtime;
 const management=installMcp(app,runtime);app.use(unsafeOriginGuard(runtime));app.use(express.json());app.use('/api/mcp',management);app.use('/api/diet',require('../src/routes/diet'));
 app.use((error,req,res,next)=>res.status(error.status||500).json({error:'safe failure'}));
 async function request(path,{method='GET',body,headers={},redirect='manual'}={}){const r=await fetch(base+path,{method,redirect,headers,...(body!==undefined?{body:typeof body==='string'?body:JSON.stringify(body)}:{})});const text=await r.text();return {status:r.status,headers:r.headers,body:text?JSON.parse(text):null};}
 const json={'Content-Type':'application/json'},own={...json,Authorization:'Bearer '+tokens[0],Origin:runtime.webUrl};
 assert.equal((await request('/mcp')).status,401);
 assert.match((await request('/mcp')).headers.get('www-authenticate'),/resource_metadata/);
 const meta=await request('/.well-known/oauth-authorization-server');assert.equal(meta.body.code_challenge_methods_supported[0],'S256');
 const register=await request('/register',{method:'POST',headers:json,body:{client_name:'Codex fixture',redirect_uris:['http://127.0.0.1:45678/callback'],token_endpoint_auth_method:'none',grant_types:['authorization_code','refresh_token'],response_types:['code']}});
 assert.equal(register.status,201,JSON.stringify(register.body));const client=register.body.client_id;
 assert.equal((await request('/register',{method:'POST',headers:{...json,Origin:'https://evil.test'},body:{}})).status,403);
 const verifier='a'.repeat(43),challenge=crypto.createHash('sha256').update(verifier).digest('base64url');
 const params=new URLSearchParams({client_id:client,redirect_uri:'http://127.0.0.1:45678/callback',response_type:'code',code_challenge:challenge,code_challenge_method:'S256',scope:'diet:read',state:'fixture-state',resource});
 const ar=await fetch(base+'/authorize?'+params,{redirect:'manual',headers:{Cookie:'ignored_browser_cookie=value'}});assert.equal(ar.status,302);const ticket=new URLSearchParams(new URL(ar.headers.get('location')).hash.split('?')[1]).get('mcp_request');
 assert.equal((await request('/api/mcp/consent/'+ticket,{headers:{Authorization:'Bearer '+tokens[2]}})).status,403);
 const consent=await request('/api/mcp/consent/'+ticket,{headers:own});assert.equal(consent.body.account,users[0].email);
 assert.equal((await request('/api/mcp/consent/'+ticket,{method:'POST',headers:{...own,Origin:'https://evil.test'},body:{allow:true}})).status,403);
 const approved=await request('/api/mcp/consent/'+ticket,{method:'POST',headers:own,body:{allow:true}});assert.equal(approved.status,200,JSON.stringify(approved.body));const cb=new URL(approved.body.redirectUrl);assert.equal(cb.searchParams.get('state'),'fixture-state');
 const form={'Content-Type':'application/x-www-form-urlencoded'};
 const tokenInput={client_id:client,grant_type:'authorization_code',code:cb.searchParams.get('code'),redirect_uri:'http://127.0.0.1:45678/callback',code_verifier:verifier,resource};
 const exchange=input=>request('/token',{method:'POST',headers:form,body:new URLSearchParams(input).toString()});
 assert.equal((await exchange({...tokenInput,code_verifier:'b'.repeat(43)})).status,400);
 const issued=await exchange(tokenInput);assert.equal(issued.status,200,JSON.stringify(issued.body));let access=issued.body.access_token;const refresh=issued.body.refresh_token;
 assert.equal((await exchange(tokenInput)).status,400);
 const nutrition={calories:301,proteinGrams:7.3,carbohydrateGrams:63.1,fatGrams:1.3,fiberGrams:2.1};const date=require('../src/services/dietHistory').historyRange(undefined,'America/Los_Angeles').latest;
 await Meal.create(users.slice(0,2).map(u=>({userId:u._id,consumedOn:date,name:u.name+' meal',mealType:'lunch',...nutrition})));
 await WaterEntry.create({userId:users[0]._id,consumedOn:date,amountMilliliters:250});
 await Library.create(users.slice(0,2).map(u=>({ownerId:u._id,name:u.name+' library',nutritionSource:'Mixed',items:[{name:u.name+' rice',normalizedName:u.name+' rice',category:'lunch',servingDescription:'bowl',...nutrition}]})));
 const foreign=await Library.findOne({ownerId:users[1]._id});await Reference.create({userId:users[0]._id,libraryId:foreign._id,kind:'shared'});
 const before=await Meal.countDocuments();
 const rpc=(method,params={},extra={})=>request('/mcp',{method:'POST',headers:{...json,Accept:'application/json, text/event-stream',Authorization:'Bearer '+access,...extra},body:{jsonrpc:'2.0',id:1,method,params}});
 const init=await rpc('initialize',{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'fixture',version:'1'}});assert.equal(init.status,200,JSON.stringify(init.body));
 const listed=await rpc('tools/list');assert.equal(listed.body.result.tools.length,5);assert.ok(listed.body.result.tools.every(tool=>tool.annotations.readOnlyHint));
 const day=await rpc('tools/call',{name:'diet_get_day',arguments:{date}});assert.equal(day.body.result.structuredContent.meals.length,1);assert.equal(day.body.result.structuredContent.meals[0].name,'owner meal');
 const expected=await request('/api/diet/days/'+date,{headers:own});assert.equal(expected.status,200);assert.deepEqual(day.body.result.structuredContent.totals,expected.body.totals);assert.equal(day.body.result.structuredContent.totals.calories,301);
 const search=await rpc('tools/call',{name:'diet_search_personal_meals',arguments:{}});assert.deepEqual(search.body.result.structuredContent.meals.map(m=>m.name),['owner rice']);
 assert.equal((await rpc('tools/call',{name:'diet_get_day',arguments:{date,userId:String(users[1]._id)}})).body.result.isError,true);
 assert.equal((await rpc('tools/call',{name:'add_meal',arguments:{}})).body.result.isError,true);
 assert.equal((await rpc('tools/list',{}, {'X-Astitva-Member':String(users[1]._id)})).status,403);
 assert.equal((await rpc('tools/list',{}, {Cookie:'session=anything'})).status,403);
 const history=await rpc('tools/call',{name:'diet_get_history',arguments:{start:date,end:date,timezone:'America/Los_Angeles'}});assert.equal(history.body.result.structuredContent.days[0].mealCount,1);
 const recent=await rpc('tools/call',{name:'diet_get_recent_meals',arguments:{}});assert.equal(recent.body.result.structuredContent.meals[0].name,'owner meal');
 await Library.create({ownerId:users[0]._id,name:'Bulk fixture',nutritionSource:'Mixed',items:Array.from({length:51},(_,i)=>({name:'bulk '+String(i).padStart(2,'0'),normalizedName:'bulk '+i,category:'lunch',servingDescription:'bowl',...nutrition}))});
 const truncated=await rpc('tools/call',{name:'diet_search_personal_meals',arguments:{search:'bulk'}});assert.equal(truncated.body.result.structuredContent.meals.length,50);assert.equal(truncated.body.result.structuredContent.hasMore,true);
 assert.equal((await rpc('tools/call',{name:'diet_get_day',arguments:{date:'2026-02-30'}})).body.result.isError,true);
 assert.equal((await exchange({...tokenInput,resource:base+'/wrong'})).status,400);

 const refreshed=await exchange({client_id:client,grant_type:'refresh_token',refresh_token:refresh,resource});assert.equal(refreshed.status,200,JSON.stringify(refreshed.body));
 assert.equal((await rpc('tools/list')).status,401);access=refreshed.body.access_token;
 assert.equal((await exchange({client_id:client,grant_type:'refresh_token',refresh_token:refresh,resource})).status,400);
 await Flags.updateOne({email:users[0].email},{$set:{diet:false}});assert.equal((await rpc('tools/list')).status,403);await Flags.updateOne({email:users[0].email},{$set:{diet:true}});
 await Bucket.findOneAndUpdate({key:hash('tools:'+users[0]._id+':'+Math.floor(Date.now()/60000))},{$set:{count:30}});
 assert.equal((await rpc('tools/call',{name:'diet_get_targets',arguments:{}})).status,429);
 await Flags.updateOne({email:users[0].email},{$unset:{mcp:''}});
 assert.equal((await rpc('tools/list')).status,403);
 assert.equal((await request('/api/mcp/connections',{headers:own})).status,403);
 assert.equal((await exchange({client_id:client,grant_type:'refresh_token',refresh_token:refreshed.body.refresh_token,resource})).status,400);
 assert.equal((await request('/api/diet/days/'+date,{headers:own})).status,200);
 await Flags.updateOne({email:users[0].email},{$set:{mcp:false}});
 assert.equal((await rpc('tools/list')).status,403);
 await Flags.updateOne({email:users[0].email},{$set:{mcp:true}});
 assert.equal((await rpc('tools/list')).status,200);
 const connections=await request('/api/mcp/connections',{headers:own});assert.equal(connections.body.connections.length,1);const id=connections.body.connections[0].id;
 assert.equal((await request('/api/mcp/connections/'+id,{method:'DELETE',headers:{...own,Authorization:'Bearer '+tokens[1]}})).status,404);
 assert.equal((await request('/api/mcp/connections/'+id,{method:'DELETE',headers:own})).status,204);
 assert.equal((await rpc('tools/list')).status,401);
 assert.equal((await exchange({client_id:client,grant_type:'refresh_token',refresh_token:refreshed.body.refresh_token,resource})).status,400);
 assert.equal((await request('/revoke',{method:'POST',headers:form,body:new URLSearchParams({client_id:client,token:access}).toString()})).status,200);
 assert.equal(await Meal.countDocuments(),before);
 assert.ok(await Session.exists({tokenHash:hash(tokens[0])}));
});
