const test=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');
test('F023 membership, audience, READONLY writes, moderation, paging and private photos',{skip:process.env.ASTITVA_TEST_FAMILY_SOCIAL!=='1',timeout:60000},async t=>{
  Object.assign(process.env,{ASTITVA_ENV:'dev',MONGODB_URL:'mongodb://127.0.0.1:27017/astitva',PLAID_ENV:'sandbox',PLAID_CLIENT_ID:'fixture',PLAID_SECRET:'fixture',FINANCE_TOKEN_ENCRYPTION_KEY:'11'.repeat(32)});
  const mongoose=require('mongoose');const express=require('express');const User=require('../src/models/User');const Session=require('../src/models/Session');
  const {Family}=require('../src/models/Family');const {FamilyPost:Post,FamilyPostComment:Comment}=require('../src/models/FamilyPost');
  const db='astitva_f023_fixture_'+crypto.randomBytes(8).toString('hex');
  let server; t.after(async()=>{if(server)await new Promise(r=>server.close(r));if(mongoose.connection.readyState===1)await mongoose.connection.dropDatabase();await mongoose.disconnect();});
  await mongoose.connect(`mongodb://127.0.0.1:27017/${db}`,{serverSelectionTimeoutMS:2500});
  const ids=Array.from({length:6},()=>new mongoose.Types.ObjectId());const tokens=ids.map(()=>crypto.randomBytes(32).toString('hex'));
  for(let i=0;i<ids.length;i++){
    await User.create({_id:ids[i],name:`Fixture ${i}`,email:`fixture-${i}@example.invalid`,passwordHash:'fixture',emailVerifiedAt:new Date()});
    await Session.create({userId:ids[i],tokenHash:crypto.createHash('sha256').update(tokens[i]).digest('hex'),expiresAt:new Date(Date.now()+3600000)});
  }
  const f=await Family.create({creatorId:ids[0],people:ids.slice(0,5).map((id,i)=>({name:`Person ${i}`,userId:i===4?null:id,status:i<3?'ACCEPTED':i===3?'PENDING':'NON_USER',role:i===0?'ADMIN':'READONLY'}))});
  const other=await Family.create({creatorId:ids[5],people:[{name:'Other',userId:ids[5],status:'ACCEPTED',role:'ADMIN'}]});
  const app=express();app.locals.runtime={isProduction:false};app.use(require('cookie-parser')());app.use(express.json());app.use('/api/family',require('../src/routes/family'));app.use((e,req,res,next)=>res.status(500).json({error:e.message}));
  server=await new Promise(r=>{const s=app.listen(0,'127.0.0.1',()=>r(s));});const root=`http://127.0.0.1:${server.address().port}/api/family`;
  async function request(method,path,body,account=0){const multipart=body instanceof FormData;const response=await fetch(root+path,{method,headers:{...(account===null?{}:{Cookie:`astitva_dev_session=${tokens[account]}`}),...(!multipart?{'Content-Type':'application/json'}:{})},...(body!==undefined?{body:multipart?body:JSON.stringify(body)}:{})});return {status:response.status,headers:response.headers,body:response.status===204?null:response.headers.get('content-type')?.startsWith('image/')?Buffer.from(await response.arrayBuffer()):await response.json()};}
  const base=`/${f._id}/posts`;const payload={text:'Family hello',type:'update',audience:'family',recipientIds:[]};
  assert.equal((await request('GET',base,undefined,null)).status,401);
  for(const i of [3,4,5])assert.equal((await request('GET',base,undefined,i)).status,404);
  const publicPost=await request('POST',base,payload,1);assert.equal(publicPost.status,201,'READONLY may post');
  const publicId=publicPost.body.post.id;
  assert.equal((await request('GET',base,undefined,2)).body.posts[0].id,publicId);
  assert.equal((await request('PATCH',`${base}/${publicId}`,{...payload,text:'forged',version:1},0)).status,403);
  assert.equal((await request('POST',base,{...payload,audience:'selected',recipientIds:[String(ids[3])]})).status,400);
  const selected=await request('POST',base,{...payload,type:'announcement',audience:'selected',recipientIds:[String(ids[1])]});assert.equal(selected.status,201);
  const privateId=selected.body.post.id;
  assert.equal((await request('GET',base,undefined,2)).body.posts.some(p=>p.id===privateId),false);
  for(const suffix of ['comments','photo'])assert.equal((await request('GET',`${base}/${privateId}/${suffix}`,undefined,2)).status,404);
  for(const suffix of ['comments','reactions'])assert.equal((await request('POST',`${base}/${privateId}/${suffix}`,{text:'forged'},2)).status,404);
  assert.equal((await request('DELETE',`${base}/${privateId}`,undefined,2)).status,404);
  assert.equal((await request('POST',`${base}/${privateId}/reactions`,{},1)).status,204);
  assert.equal((await request('POST',`${base}/${privateId}/reactions`,{},1)).status,204);
  assert.equal((await request('GET',base,undefined,1)).body.posts.find(p=>p.id===privateId).reactionCount,1);
  for(let i=0;i<3;i++)assert.equal((await request('POST',`${base}/${privateId}/comments`,{text:`Comment ${i}`},1)).status,201);
  const first=await request('GET',`${base}/${privateId}/comments?limit=2`,undefined,1);assert.equal(first.body.comments.length,2);assert.ok(first.body.nextCursor);
  assert.equal((await request('GET',`${base}/${privateId}/comments?limit=2&before=${first.body.nextCursor}`,undefined,1)).body.comments.length,1);
  assert.equal((await request('PUT',`${base}/${privateId}/pin`,{pinned:true},1)).status,200,'any visible accepted member may pin');
  assert.equal((await request('GET',base,undefined,2)).body.pinned,null,'pin does not leak selected post');
  await Family.updateOne({_id:f._id,'people.userId':ids[1]},{$set:{'people.$.status':'PENDING'}});
  assert.equal((await request('GET',base,undefined,1)).status,404);
  await Family.updateOne({_id:f._id,'people.userId':ids[1]},{$set:{'people.$.status':'ACCEPTED'}});
  assert.equal((await request('GET',base,undefined,1)).body.posts.some(p=>p.id===privateId),true,'rejoining restores selected access');
  const second=await request('POST',base,{...payload,type:'announcement'});assert.equal((await request('PUT',`${base}/${second.body.post.id}/pin`,{pinned:true},2)).status,200);
  assert.equal((await request('GET',base)).body.pinned.id,second.body.post.id,'single pin replacement');
  const edited=await request('PATCH',`${base}/${privateId}`,{...payload,text:'Edited',version:1});assert.equal(edited.status,200);
  assert.equal((await request('PATCH',`${base}/${privateId}`,{...payload,text:'stale',version:1})).status,409);
  const image=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64');
  const form=new FormData();form.append('payload',JSON.stringify({...payload,audience:'selected',recipientIds:[String(ids[1])]}));form.append('photo',new Blob([image],{type:'image/png'}),'fixture.png');
  const uploaded=await request('POST',base,form);assert.equal(uploaded.status,201);
  const imageId=uploaded.body.post.id;const photo=await request('GET',`${base}/${imageId}/photo`,undefined,1);assert.equal(photo.status,200);assert.deepEqual(photo.body,image);assert.equal(photo.headers.get('x-content-type-options'),'nosniff');
  assert.equal((await request('GET',`${base}/${imageId}/photo`,undefined,2)).status,404);
  const bad=new FormData();bad.append('payload',JSON.stringify(payload));bad.append('photo',new Blob(['<svg/>'],{type:'image/png'}),'fake.png');assert.equal((await request('POST',base,bad)).status,400);
  const large=new FormData();large.append('payload',JSON.stringify(payload));large.append('photo',new Blob([Buffer.alloc(2*1024*1024+1)],{type:'image/png'}),'large.png');assert.equal((await request('POST',base,large)).status,413);
  assert.equal((await request('GET',`/${other._id}/posts/${imageId}/photo`,undefined,5)).status,404);
  const page=await request('GET',base+'?limit=2');assert.equal(page.body.posts.length,2);assert.ok(page.body.nextCursor);
  const next=await request('GET',base+'?limit=2&before='+page.body.nextCursor);assert.ok(next.body.posts.every(p=>!page.body.posts.some(q=>q.id===p.id)));
  assert.equal((await request('DELETE',`${base}/${imageId}`,undefined,1)).status,204,'visible READONLY can remove');
  const removed=await Post.findById(imageId);assert.equal(removed.photo?.data,undefined);assert.equal(removed.deleted,true);
  assert.equal((await request('GET',`${base}/${imageId}/photo`)).status,404);
  assert.equal((await request('DELETE',`${base}/${privateId}`,undefined,1)).status,204);
  assert.equal(await Comment.countDocuments({postId:privateId}),0);
  assert.equal((await request('GET',`${base}/${privateId}/comments`)).status,404);
});
