const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
test('F036 co-editing, ownership isolation, feature/role denial, premium exclusion and claiming',{skip:process.env.ASTITVA_TEST_MANAGED_WORKSPACE!=='1',timeout:60000},async t=>{
 const uri=process.env.F036_TEST_MONGODB_URL;if(!/^mongodb:\/\/127\.0\.0\.1:27135\/f036_fixture_[a-z0-9_]+\?replicaSet=f035test$/.test(uri||''))throw Error('Disposable f036_fixture_* database required.');
 Object.assign(process.env,{ASTITVA_ENV:'dev',MONGODB_URL:'mongodb://127.0.0.1:27017/astitva',PLAID_ENV:'sandbox',PLAID_CLIENT_ID:'fixture',PLAID_SECRET:'fixture',FINANCE_TOKEN_ENCRYPTION_KEY:'11'.repeat(32)});
 const m=require('mongoose');await m.connect(uri);t.after(async()=>{await m.connection.dropDatabase();await m.disconnect();});
 const User=require('../src/models/User'),Session=require('../src/models/Session'),Flags=require('../src/models/InvitedEmail'),{Person,Unit,Membership,Relationship}=require('../src/models/FamilyUnit'),{Meal}=require('../src/models/Diet');
 const users=await User.create(['Admin','Editor','ReadOnly','Claimant'].map((name,i)=>({name,email:`f036-${i}@example.invalid`,passwordHash:'fixture',emailVerifiedAt:new Date()})));
 await Flags.create(users.map(u=>({email:u.email,family:true,diet:true,priorities:true,finance:true,chat:true})));
 const people=await Person.create(users.slice(0,3).map(u=>({name:u.name,userId:u._id}))),child=await Person.create({name:'Child',gender:'male'}),unit=await Unit.create({creatorId:users[0]._id,anchors:[{personId:people[0]._id,relationship:'son'}]});
 await Membership.create(people.map((p,i)=>({personId:p._id,unitId:unit._id,role:['ADMIN','EDITOR','READONLY'][i]})).concat([{personId:child._id,unitId:unit._id}]));
 await Relationship.create({unitId:unit._id,type:'parent',fromPersonId:people[0]._id,toPersonId:child._id});await require('../src/services/familyUnits').project(unit._id);
 const tokens=users.map(()=>crypto.randomBytes(32).toString('hex'));await Session.create(users.map((u,i)=>({userId:u._id,tokenHash:crypto.createHash('sha256').update(tokens[i]).digest('hex'),expiresAt:new Date(Date.now()+3600000)})));
 const app=require('../src/app').createApp(),server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));
 const api=async(method,path,actor=0,body,managed=true)=>{const response=await fetch(`http://127.0.0.1:${server.address().port}${path}`,{method,headers:{Authorization:`Bearer ${tokens[actor]}`,Origin:'http://localhost:3000','Content-Type':'application/json','X-Time-Zone':'UTC',...(managed?{'X-Astitva-Member':String(child._id),'X-Astitva-Family':String(unit._id)}:{})},body:body?JSON.stringify(body):undefined});return {status:response.status,body:response.status===204?null:await response.json()};};
 const context=await api('GET',`/api/family/units/${unit._id}/people/${child._id}/managed-workspace`,0,undefined,false);assert.equal(context.status,200);assert.deepEqual(context.body.modules,['diet','priorities','family']);
 const input={date:'2026-10-07',name:'Fixture meal',mealType:'breakfast',nutrition:{calories:100,proteinGrams:5,carbohydrateGrams:15,fatGrams:2,fiberGrams:1}};
 let result=await api('POST','/api/diet/meals',0,input);assert.equal(result.status,201,JSON.stringify(result.body));assert.equal(await Meal.countDocuments({userId:child._id}),1);assert.equal(await Meal.countDocuments({userId:users[0]._id}),0);
 result=await api('GET','/api/diet/days/2026-10-07',1);assert.equal(result.status,200);assert.equal(result.body.meals.length,1);
 const meal=(await api('GET','/api/diet/days/2026-10-07',1)).body.meals[0];assert.equal((await api('PATCH',`/api/diet/meals/${meal.id}`,1,{nutrition:{calories:120,proteinGrams:5,carbohydrateGrams:15,fatGrams:2,fiberGrams:1}})).status,200);assert.equal((await api('GET','/api/diet/days/2026-10-07')).body.meals[0].nutrition.calories,120);
 assert.equal((await api('POST','/api/priorities/days/2020-01-01/priorities',0,{title:'Managed priority'})).status,201);assert.equal((await api('GET','/api/priorities/days/2020-01-01',1)).body.priorities.length,1);
 assert.equal((await api('POST','/api/diet/meals',2,input)).status,403);
 await Flags.updateOne({email:users[1].email},{$set:{diet:false}});assert.equal((await api('GET','/api/diet/days/2026-10-07',1)).status,403);
 for(const route of ['/api/finance/summary','/api/chat/conversations','/api/admin/users'])assert.equal((await api('GET',route)).status,403);
 const managedPath=`/api/family/units/${unit._id}/people/${child._id}/managed-workspace`;const beforeDetails=await api('GET',managedPath,0,undefined,false);assert.equal((await api('PATCH',managedPath,1,{expectedRevision:beforeDetails.body.revision,details:{note:'Co-managed note'}},false)).status,200);
 const S=require('../src/services/familyUnits');const current=await Unit.findById(unit._id);const request=await S.newRequest(users[0],{sourceUnitId:String(unit._id),relationship:'son',targetEmail:users[3].email,existingPersonId:String(child._id),expectedRevision:current.revision,idempotencyKey:'fixture-claim'});await S.relationshipDecision(users[3],String(request._id),{decision:'accept',expectedRevision:request.revision});
 assert.equal((await api('PATCH',managedPath,0,{expectedRevision:0,details:{note:'Unauthorized after linking'}},false)).status,403);
 assert.equal(await Meal.countDocuments({userId:child._id}),0);assert.equal(await Meal.countDocuments({userId:users[3]._id}),1);assert.equal((await api('GET','/api/diet/days/2026-10-07')).status,403);
 assert.equal((await api('GET','/api/diet/days/2026-10-07',3,undefined,false)).body.meals.length,1);
});
