const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
test('F037 CSV, ownership, sharing, snapshots, Admin review, deletion and migration',{skip:process.env.ASTITVA_TEST_MEAL_LIBRARIES!=='1',timeout:60000},async t=>{
 const uri=process.env.F037_TEST_MONGODB_URL;if(!/^mongodb:\/\/127\.0\.0\.1:27135\/f037_fixture_[a-z0-9_]+\?replicaSet=f035test$/.test(uri||''))throw Error('Disposable F037 replica-set fixture required.');
 Object.assign(process.env,{ASTITVA_ENV:'dev',MONGODB_URL:'mongodb://127.0.0.1:27017/astitva',PLAID_ENV:'sandbox',PLAID_CLIENT_ID:'fixture',PLAID_SECRET:'fixture',FINANCE_TOKEN_ENCRYPTION_KEY:'11'.repeat(32),ADMIN_EMAILS:'admin@example.invalid'});
 const m=require('mongoose');await m.connect(uri);t.after(async()=>{await m.connection.dropDatabase();await m.disconnect()});const User=require('../src/models/User'),Session=require('../src/models/Session'),Flags=require('../src/models/InvitedEmail'),{Library,Reference}=require('../src/models/MealLibrary'),{Meal,LibraryMeal}=require('../src/models/Diet');await Promise.all([Library.init(),Reference.init(),LibraryMeal.init()]);
 const users=await User.create(['Owner','Recipient','Other','Admin'].map((name,i)=>({name,email:i===3?'admin@example.invalid':name.toLowerCase()+'@example.invalid',passwordHash:'fixture',emailVerifiedAt:new Date()})));await Flags.create(users.map(u=>({email:u.email,diet:true,family:true})));const tokens=users.map(()=>crypto.randomBytes(32).toString('hex'));await Session.create(users.map((u,i)=>({userId:u._id,tokenHash:crypto.createHash('sha256').update(tokens[i]).digest('hex'),expiresAt:new Date(Date.now()+3600000)})));
 const server=require('../src/app').createApp().listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));
 const api=async(method,path,body,actor=0,extraHeaders={})=>{const res=await fetch(`http://127.0.0.1:${server.address().port}${path}`,{method,headers:{Authorization:'Bearer '+tokens[actor],Origin:'http://localhost:3000',...extraHeaders,...(body instanceof FormData?{}:{'Content-Type':'application/json'})},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});return {status:res.status,body:res.status===204?null:await res.json()}};
 const base='/api/diet/libraries';const headers=require('../src/services/diet').csvHeaders;const form=new FormData();form.append('file',new Blob([headers.join(',')+'\nRice,lunch,1 bowl,200,4,40,2,1,,\nBad,invalid,1 bowl,200,4,40,2,1,,\n'],{type:'text/csv'}),'meals.csv');let r=await api('POST',base+'/import-preview',form);assert.equal(r.status,200,JSON.stringify(r.body));assert.equal(r.body.validRows.length,1);assert.equal(r.body.invalidRows.length,1);assert.equal(await Library.countDocuments(),0);const rows=r.body.validRows;
 r=await api('POST',base,{name:'Shared meals',nutritionSource:'AI estimates',rows});assert.equal(r.status,201,JSON.stringify(r.body));let l=r.body.library;const id=l.id;let item=l.items[0];const path=base+'/'+id;
 assert.equal((await api('GET',path,null,1)).status,404);assert.equal((await api('PATCH',path,{expectedRevision:l.revision,name:'Forged'},1)).status,403);
 r=await api('PUT',path+'/access',{expectedRevision:l.revision,email:users[1].email});assert.equal(r.status,200,JSON.stringify(r.body));assert.equal((await api('GET',path,null,1)).body.library.items.length,1);assert.equal(await Library.countDocuments(),1);l=(await api('GET',path)).body.library;
 assert.equal((await api('DELETE',path+'/access/'+users[1]._id,{expectedRevision:l.revision})).status,204);assert.equal((await api('GET',path,null,1)).status,404);l=(await api('GET',path)).body.library;assert.equal((await api('PUT',path+'/access',{expectedRevision:l.revision,email:users[1].email})).status,200);l=(await api('GET',path)).body.library;
 r=await api('POST',path+'/submit',{expectedRevision:l.revision});assert.equal(r.status,200);l=r.body.library;assert.equal((await api('PATCH',path,{expectedRevision:l.revision,name:'Locked'})).status,409);assert.equal((await api('GET','/api/admin/meal-libraries',null,0)).status,403);
 r=await api('POST','/api/admin/meal-libraries/'+id+'/review',{expectedRevision:l.revision,action:'publish'},3);assert.equal(r.status,200,JSON.stringify(r.body));l=r.body.library;assert.equal((await api('GET',path,null,2)).body.library.name,'Shared meals');
 r=await api('PATCH',path+'/items/'+item.id,{expectedRevision:l.revision,item:{name:item.name,category:item.category,servingDescription:item.servingDescription,ingredients:item.ingredients,notes:item.notes,nutrition:{...item.nutrition,calories:300}}});assert.equal(r.status,200,JSON.stringify(r.body));l=r.body.library;assert.equal((await api('GET',path,null,2)).body.library.items[0].nutrition.calories,200);assert.equal((await api('GET',path,null,1)).body.library.items[0].nutrition.calories,300);
 r=await api('POST',path+'/items/'+item.id+'/add-to-day',{date:'2026-10-07',mealType:'lunch',quantity:2},2);assert.equal(r.status,201,JSON.stringify(r.body));assert.equal((await Meal.findOne({userId:users[2]._id})).calories,400);l=(await api('GET',path)).body.library;
 assert.equal((await api('DELETE',path,{expectedRevision:l.revision-1})).status,409);assert.equal((await api('DELETE',path,{expectedRevision:l.revision})).status,204);assert.ok((await Library.findById(id)).archivedAt);assert.equal((await api('POST',path+'/items/'+item.id+'/add-to-day',{date:'2026-10-07',mealType:'lunch',quantity:1},1)).status,404);assert.equal(await Meal.countDocuments(),1);
 r=await api('POST',base,{name:'Never shared',nutritionSource:'Mixed'});const privateId=r.body.library.id;assert.equal((await api('DELETE',base+'/'+privateId,{expectedRevision:0})).status,204);assert.equal(await Library.findById(privateId),null);
 await LibraryMeal.create({userId:users[0]._id,name:'Legacy',normalizedName:'legacy',category:'lunch',servingDescription:'1 bowl',calories:100,proteinGrams:1,carbohydrateGrams:20,fatGrams:1,fiberGrams:1});const a=await api('POST',base+'/migrate-existing',{}),b=await api('POST',base+'/migrate-existing',{});assert.equal(a.status,200);assert.equal(a.body.library.id,b.body.library.id);assert.equal(await LibraryMeal.countDocuments(),1);

 const {Targets,WaterEntry}=require('../src/models/Diet');const {historyRange}=require('../src/services/dietHistory');const hr=historyRange();
 await Meal.create([{userId:users[0]._id,consumedOn:hr.latest,name:'History fixture',mealType:'lunch',calories:123,proteinGrams:4,carbohydrateGrams:20,fatGrams:3,fiberGrams:2},{userId:users[2]._id,consumedOn:hr.latest,name:'Other owner',mealType:'lunch',calories:9999,proteinGrams:4,carbohydrateGrams:20,fatGrams:3,fiberGrams:2}]);
 await WaterEntry.create({userId:users[0]._id,consumedOn:hr.latest,amountMilliliters:250});
 await Targets.create({userId:users[0]._id,calories:2000,proteinGrams:100,carbohydrateGrams:250,fatGrams:60,fiberGrams:30,waterMilliliters:2000});
 r=await api('GET','/api/diet/history');assert.equal(r.status,200,JSON.stringify(r.body));assert.equal(r.body.days.length,10);assert.equal(r.body.days.at(-1).totals.calories,123);assert.equal(r.body.days.at(-1).totals.waterMilliliters,250);assert.equal(r.body.targetBasis,'current');assert.equal(r.body.targets.calories,2000);
 assert.equal((await api('GET','/api/diet/history',null,1)).body.days.at(-1).totals.calories,0);
 assert.equal((await api('GET','/api/diet/history?end=1900-01-01')).status,400);
 assert.equal((await api('GET','/api/diet/history?timezone=Invalid')).status,400);
 const anonymous=await fetch(`http://127.0.0.1:${server.address().port}/api/diet/history`);assert.equal(anonymous.status,401);
 const {Person,Unit,Membership}=require('../src/models/FamilyUnit');const parent=await Person.create({userId:users[0]._id,name:'Parent'}),child=await Person.create({name:'Managed child'}),unit=await Unit.create({creatorId:users[0]._id});await Membership.create([{unitId:unit._id,personId:parent._id,role:'ADMIN'},{unitId:unit._id,personId:child._id,role:'READONLY'}]);const managed={'X-Astitva-Member':String(child._id),'X-Astitva-Family':String(unit._id)};

 await WaterEntry.create({userId:child._id,consumedOn:hr.latest,amountMilliliters:500});
 r=await api('GET','/api/diet/history',null,0,managed);assert.equal(r.status,200,JSON.stringify(r.body));assert.equal(r.body.days.at(-1).totals.waterMilliliters,500);assert.equal(r.body.days.at(-1).totals.calories,0);
 assert.equal((await api('GET','/api/diet/history',null,1,managed)).status,404);
 r=await api('POST',base,{name:'Child meals',nutritionSource:'Mixed'},0,managed);assert.equal(r.status,201,JSON.stringify(r.body));const childLibrary=r.body.library;assert.equal(String((await Library.findById(childLibrary.id)).ownerId),String(child._id));assert.equal((await api('PUT',base+'/'+childLibrary.id+'/access',{expectedRevision:0,email:users[1].email},0,managed)).status,403);assert.equal((await api('POST',base+'/'+childLibrary.id+'/submit',{expectedRevision:0},0,managed)).status,403);
 await require('../src/services/familyUnits').transaction(async session=>{await require('../src/services/managedWorkspace').transfer(child._id,users[2]._id,session);await Person.updateOne({_id:child._id},{$set:{userId:users[2]._id}},{session});});assert.equal(String((await Library.findById(childLibrary.id)).ownerId),String(users[2]._id));assert.equal((await api('GET',base+'/'+childLibrary.id,null,2)).body.library.owner,true);assert.equal((await api('GET',base+'/'+childLibrary.id,null,0,managed)).status,403);

});
