const mongoose=require('mongoose');const {Library,Reference}=require('../models/MealLibrary');const {LibraryMeal,Meal,fields}=require('../models/Diet');const User=require('../models/User');const D=require('./diet');
const same=(a,b)=>String(a)===String(b);const fail=(status,message)=>{throw Object.assign(Error(message),{status});};const validId=id=>typeof id==='string'&&/^[a-f0-9]{24}$/i.test(id);
function metadata(body,partial=false){if(!body||typeof body!=='object'||Array.isArray(body))fail(400,'Invalid library details.');const result={};for(const key of ['name','nutritionSource','description','tags']){if(!(key in body)){if(!partial&&['name','nutritionSource'].includes(key))fail(400,'Name and nutrition source are required.');continue;}const value=body[key];if(key==='tags'){if(!Array.isArray(value)||value.length>10||value.some(v=>typeof v!=='string'||!v.trim()||v.trim().length>40))fail(400,'Use up to 10 short tags.');result.tags=[...new Set(value.map(v=>v.trim()))];}else {if(typeof value!=='string'||value.trim().length>(key==='description'?1000:100)||key!=='description'&&!value.trim())fail(400,'Invalid '+key+'.');result[key]=value.trim();}}if(result.nutritionSource&&!['AI estimates','Product labels','Reference source','Mixed','Existing personal meals'].includes(result.nutritionSource))fail(400,'Choose a nutrition source.');return result;}
function validateItems(items){if(!Array.isArray(items)||items.length>500)fail(400,'A library supports up to 500 items.');if(new Set(items.map(i=>i.normalizedName)).size!==items.length)fail(409,'Meal names must be unique within the library.');}
function inputItem(body){const value=D.validateLibraryMeal(body);if(value.fields)fail(400,'Invalid meal: '+Object.entries(value.fields).map(([k,v])=>k+': '+v).join('; '));return value.value;}
function snapshot(l){return {name:l.name,nutritionSource:l.nutritionSource,description:l.description,tags:l.tags,items:l.items.map(i=>i.toObject?i.toObject():i),publishedAt:new Date()};}
function display(l,owner,privateAccess=false){const data=owner||privateAccess?l:l.published;if(!data)fail(404,'Library unavailable.');return {id:String(l._id),...Object.fromEntries(['name','nutritionSource','description','tags'].map(k=>[k,data[k]])),items:data.items.map(i=>({id:String(i._id),name:i.name,category:i.category,servingDescription:i.servingDescription,ingredients:i.ingredients||'',notes:i.notes||'',nutrition:D.nutritionValues(i)})),owner,revision:l.revision,reviewStatus:owner?l.reviewStatus:undefined,feedback:owner?l.feedback:undefined,archived:Boolean(l.archivedAt),hasPublished:Boolean(l.published),everDistributed:l.everDistributed};}
async function get(id,userId,write=false){if(!validId(id))fail(404,'Library not found.');const l=await Library.findById(id);if(!l||l.archivedAt)fail(404,'Library unavailable or archived.');const owner=same(l.ownerId,userId);const ref=await Reference.findOne({libraryId:id,userId});if(write&&!owner)fail(403,'Only the owner can change this library.');if(!owner&&!ref&&!l.published)fail(404,'Library not found.');if(write&&l.reviewStatus==='submitted')fail(409,'The submitted draft is locked while Admin reviews it.');return {l,owner,privateAccess:ref?.kind==='shared'};}
function revision(l,value){if(!Number.isSafeInteger(value)||value!==l.revision)fail(409,'Library changed. Reload before trying again.');}
async function save(l,expected,change){revision(l,expected);const updated=await Library.findOneAndUpdate({_id:l._id,revision:expected,archivedAt:null},{$set:change,$inc:{revision:1}},{returnDocument:'after',runValidators:true});if(!updated)fail(409,'Library changed. Reload before trying again.');return updated;}
async function transaction(work){mongoose.set('transactionAsyncLocalStorage',true);if(mongoose.transactionAsyncLocalStorage?.getStore()?.session)return work();return mongoose.connection.transaction(work);}
async function touch(l){const updated=await Library.updateOne({_id:l._id,revision:l.revision,archivedAt:null},{$inc:{revision:1}});if(updated.modifiedCount!==1)fail(409,'Library changed; try again.');}
function summary(l,owner,privateAccess=false){const {items,...data}=display(l,owner,privateAccess);return {...data,itemCount:items.length};}
async function migrate(userId){const existing=await Library.findOne({legacyOwnerId:userId});if(existing)return existing.archivedAt?null:existing;const old=await LibraryMeal.find({userId}).sort({_id:1});if(!old.length)return null;if(old.length>500)fail(409,'Existing library exceeds 500 items; split it before migration.');return transaction(async()=>{const prior=await Library.findOne({legacyOwnerId:userId});if(prior)return prior;const [l]=await Library.create([{ownerId:userId,legacyOwnerId:userId,name:'My personal meals',nutritionSource:'Existing personal meals',items:old.map(i=>({...Object.fromEntries(['name','normalizedName','category','servingDescription','ingredients','notes',...fields].map(k=>[k,i[k]])),_id:i._id}))}]);await Reference.create({libraryId:l._id,userId,kind:'owner'});return l;});}
module.exports={same,fail,validId,metadata,summary,validateItems,inputItem,snapshot,display,get,revision,save,transaction,touch,migrate};
