import MemberPortrait from './ui/MemberPortrait';
import {familyAge} from './familyAge';
import { ArrowLeft, UsersRound, ChevronDown, UserRound, Check, Sprout, Flower2, Ellipsis, Pencil } from 'lucide-react';
import {useCallback,useEffect,useRef,useState,useId} from 'react';
import Diet from './Diet';
import Priorities from './Priorities';
import {TransactionList} from './Finance';
import {Button,IconButton,FormField,LoadingState,PageHeader,SectionHeader,StatCard,StatusBanner,Surface} from './ui';
import {dietSharedData,memberKey,sharedPage} from './sharedWorkspace.js';
export function useSharedWorkspace({apiRequest,user,page}){
 const [members,setMembers]=useState([]),[selected,setSelected]=useState(null),[context,setContext]=useState(null),[error,setError]=useState(''),[version,setVersion]=useState(0),[membersError,setMembersError]=useState('');
 const seq=useRef(0),selector=useRef(null),heading=useRef(null),previousPage=useRef('profile');
 const [loading,setLoading]=useState(false);
 const loadMembers=useCallback(async()=>{try{const [r,m]=await Promise.all([apiRequest('/api/family/shared-workspace/members'),apiRequest('/api/family/units/managed-members')]);setMembers([...r.members,...m.members]);setMembersError('');}catch(e){setMembers([]);setMembersError(e.message);}},[apiRequest]);
 useEffect(()=>{if(!user.features?.family)return;loadMembers();window.addEventListener('astitva:family-updated',loadMembers);return()=>window.removeEventListener('astitva:family-updated',loadMembers);},[loadMembers,user.id,user.features?.family]);
 function exit(message=''){seq.current++;setSelected(null);setContext(null);setLoading(false);setError(message);window.location.hash=previousPage.current;requestAnimationFrame(()=>selector.current?.focus());}
 function choose(value){
  if(!value){exit();return;}
  const event=new CustomEvent('astitva:before-workspace-change',{cancelable:true});if(!window.dispatchEvent(event))return;
  // Existing modules do not expose a central dirty guard. Ask before abandoning visible forms.
  if(!selected&&document.querySelector('.app-main form')&&!window.confirm('Switch workspace and discard any unsaved form changes?'))return;
  const member=members.find(m=>memberKey(m)===value);if(!member)return;
  if(!selected)previousPage.current=page;seq.current++;setSelected(member);setContext(null);setError('');setLoading(true);setVersion(v=>v+1);
 }
 useEffect(()=>{
  if(!selected)return;let active=true;const generation=++seq.current;
  async function refresh(){const run=++seq.current;if(!selected.managed)setContext(null);setLoading(true);setError('');
   try{const c=await apiRequest(selected.managed?`/api/family/units/${selected.familyId}/people/${selected.personId}/managed-workspace`:`/api/family/${selected.familyId}/people/${selected.personId}/shared-workspace`);if(active&&run===seq.current){setContext(c);setLoading(false);}}
   catch(e){if(!active||run!==seq.current)return;setContext(null);setLoading(false);if(e.status===404||e.status===401||e.status===403){exit('Shared member access ended. You are back in your own workspace.');loadMembers();}else setError(e.message);}
  }
  refresh();const timer=window.setInterval(refresh,60000);window.addEventListener('focus',refresh);
  return()=>{active=false;if(seq.current===generation)seq.current++;window.clearInterval(timer);window.removeEventListener('focus',refresh);};
 },[selected,version,apiRequest,page]);
 useEffect(()=>{if(selected)requestAnimationFrame(()=>heading.current?.focus());},[selected]);
 const selectedPage=selected?(selected.managed?(context?.modules.includes(page)?page:context?.modules[0]||''):sharedPage(context?.modules||[],page)):page;
 useEffect(()=>{if(selected&&context&&selectedPage&&page!==selectedPage)window.location.hash=selectedPage;},[selected,context,page,selectedPage]);
 const denied=useCallback(e=>{seq.current++;setContext(null);setError(e.message);setVersion(v=>v+1);},[]);
 const controls=user.features?.family&&(page==='family'||selected)?<div className="shared-workspace-controls">{selected&&<IconButton icon={ArrowLeft} label="Back to my profile" onClick={()=>exit()}/>}<MemberPicker members={members} selected={selected} onChoose={choose} triggerRef={selector}/>{!selected&&membersError&&<span role="alert">{membersError} <Button onClick={loadMembers}>Retry members</Button></span>}</div>:null;
 const notice=selected?<div className="shared-context-banner"><h1 ref={heading} tabIndex={-1}>{selected.managed?`Managing ${selected.name}'s workspace`:`Viewing ${selected.name}'s shared data · Read only`}</h1></div>:null;
 let content=null;
 if(selected){content=<>{notice}{error&&<StatusBanner role="alert" tone="error">{error} <Button onClick={()=>setVersion(v=>v+1)}>Retry</Button></StatusBanner>}{loading&&<LoadingState>Loading shared workspace…</LoadingState>}{context&&!context.modules.length&&<StatusBanner>{selected.managed?'No general features are enabled for your account.':`${selected.name} has not shared any available modules with you.`}</StatusBanner>}{context&&selectedPage&&(selected.managed?<ManagedModule key={memberKey(selected)} module={selectedPage} context={context} apiRequest={apiRequest} onDenied={denied}/>:<SharedModule key={`${memberKey(selected)}:${selectedPage}:${version}:${context.owner.userId}`} module={selectedPage} context={context} apiRequest={apiRequest} onDenied={denied}/> )}</>;}
 return {selected,modules:context?.modules||[],controls,content,notice:!selected&&error?<StatusBanner role="status">{error}</StatusBanner>:null,page:selectedPage};
}
function SharedModule({module,context,apiRequest,onDenied}){
 const active=useRef(true);useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);
 const read=useCallback(async query=>{try{return await apiRequest(`/api/family/${context.familyId}/shared/${context.owner.userId}/${module}${query?'?'+query:''}`);}catch(e){if(active.current&&(e.status===401||e.status===403||e.status===404||e.status===409))onDenied(e);throw e;}},[apiRequest,context.familyId,context.owner.userId,module,onDenied]);
 const loadDay=useCallback(async date=>dietSharedData(await read(`date=${date}`)),[read]);
 if(module==='diet')return <Diet readOnly loadDay={loadDay}/>;
 return <SharedInformation module={module} read={read}/>;
}
function SharedInformation({module,read}){
 const [month,setMonth]=useState(()=>new Date().toISOString().slice(0,7)),[data,setData]=useState(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setData(null);setError('');read(module==='finance'?`month=${month}`:'').then(r=>{if(active)setData(r);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[read,module,month,retry]);
 return <section className={`profile-content ${module==='finance'?'finance-page':'family-page'}`}><PageHeader eyebrow="Shared / Read only" title={module==='finance'?'Finance':'Family'}/>{module==='finance'&&<FormField label="Finance month"><input type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></FormField>}{error&&<StatusBanner role="alert" tone="error">{error} <Button onClick={()=>setRetry(v=>v+1)}>Retry</Button></StatusBanner>}{!data&&!error&&<LoadingState>Loading shared information…</LoadingState>}{data&&(module==='finance'?<><SectionHeader title="Accounts"/><div className="finance-detail-grid">{data.accounts.map(a=><StatCard key={a._id} label={a.name} value={a.currentBalance==null?'Unavailable':`${a.currentBalance} ${a.currency}`} helper={a.balanceAsOf?`Balance as of ${a.balanceAsOf}`:undefined}/>)}</div>{!data.accounts.length&&<p>No shared accounts.</p>}<section className="finance-section"><h2>Transactions</h2><p>Up to 100 transactions for the selected month; this is not a complete monthly spending report.</p><TransactionList transactions={data.transactions.map(t=>({...t,id:t._id}))}/></section><section className="finance-section"><h2>Holdings</h2><div className="finance-table">{data.holdings.map(h=><article key={h._id}><div><strong>{h.name}</strong><span>{h.tickerSymbol}</span></div><span>{h.quantity} shares</span><strong>{h.marketValue??'Unavailable'} {h.currency}</strong></article>)}</div>{!data.holdings.length&&<p>No shared holdings.</p>}</section></>:<SharedFamilyTree data={data}/>)}</section>;
}

function ManagedModule({module,context,apiRequest,onDenied}){
 const managedRequest=useCallback(async(path,options={})=>{try{return await apiRequest(path,{...options,headers:{...options.headers,'X-Astitva-Member':context.owner.personId,'X-Astitva-Family':context.familyId}});}catch(error){if([401,403,404].includes(error.status))onDenied(error);throw error;}},[apiRequest,context.owner.personId,context.familyId,onDenied]);
 if(module==='diet')return <Diet key={context.owner.personId} apiRequest={managedRequest}/>;
 if(module==='priorities')return <Priorities key={context.owner.personId} apiRequest={managedRequest}/>;
 return <ManagedFamily context={context} apiRequest={apiRequest}/>;
}
function ManagedFamily({context,apiRequest}){
 const [revision,setRevision]=useState(context.revision);useEffect(()=>setRevision(context.revision),[context.revision]);
 const [details,setDetails]=useState(null),[people,setPeople]=useState(context.people),[error,setError]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>setPeople(context.people),[context.people]);
 return <><SharedFamilyTree data={{owner:context.owner,readOnly:false,people:people.map(person=>({...person,...person.details}))}} onEdit={person=>{setError('');setDetails({...person});}}/>{details&&<form className="family-card-details" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const saved=await apiRequest(`/api/family/units/${context.familyId}/people/${context.owner.personId}/managed-workspace`,{method:'PATCH',body:JSON.stringify({expectedRevision:revision,details:{preferredName:details.preferredName||null,birthDate:details.birthDate||null,note:details.note||null}})});setRevision(saved.revision);setPeople(current=>current.map(person=>person.id===context.owner.personId?{...person,details:{...details}}:person));setDetails(null);}catch(e){setError(e.message);}finally{setBusy(false);}}}><FormField label="Preferred name"><input disabled={busy} maxLength={80} value={details.preferredName||''} onChange={e=>setDetails({...details,preferredName:e.target.value})}/></FormField><FormField label="Birth date"><input disabled={busy} type="date" value={details.birthDate||''} onChange={e=>setDetails({...details,birthDate:e.target.value})}/></FormField><FormField label="Family note"><textarea disabled={busy} maxLength={1000} value={details.note||''} onChange={e=>setDetails({...details,note:e.target.value})}/></FormField>{error&&<p role="alert">{error}</p>}<Button type="submit" disabled={busy}>Save</Button><Button type="button" disabled={busy} onClick={()=>setDetails(null)}>Cancel</Button></form>}</>;
}


function MemberPicker({members,selected,onChoose,triggerRef}){
 const [open,setOpen]=useState(false),root=useRef(null),list=useRef(null),id=useId();
 const options=[{key:'',name:'My profile',type:'Self'},...members.map(m=>({key:memberKey(m),name:m.name,type:m.managed?'Non User':'Member',contexts:m.contexts}))];
 const value=selected?memberKey(selected):'';
 useEffect(()=>{if(!open)return;const close=e=>{if(!root.current?.contains(e.target))setOpen(false);};document.addEventListener('pointerdown',close);requestAnimationFrame(()=>{const buttons=list.current?.querySelectorAll('[role="option"]');buttons?.[Math.max(0,options.findIndex(o=>o.key===value))]?.focus();});return()=>document.removeEventListener('pointerdown',close);},[open]);
 function choose(key){onChoose(key);setOpen(false);triggerRef.current?.focus();}
 function keys(e){const buttons=[...list.current.querySelectorAll('[role="option"]')],index=buttons.indexOf(document.activeElement);let next;
 if(e.key==='ArrowDown')next=(index+1)%buttons.length;if(e.key==='ArrowUp')next=(index-1+buttons.length)%buttons.length;if(e.key==='Home')next=0;if(e.key==='End')next=buttons.length-1;
 if(next!==undefined){e.preventDefault();buttons[next]?.focus();}if(e.key==='Escape'){e.preventDefault();setOpen(false);triggerRef.current?.focus();}if(e.key==='Tab')setOpen(false);
 }
 return <div className={`family-member-selector ${selected?'is-shared':''}`} ref={root} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false);}}><button ref={triggerRef} type="button" className="family-member-selector-trigger" title={selected?`Viewing ${selected.name}`:'View a family member'} aria-label={selected?`Choose family member. Current: ${selected.name}`:'View a family member'} aria-haspopup="listbox" aria-expanded={open} aria-controls={id} onClick={()=>setOpen(v=>!v)} onKeyDown={e=>{if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();setOpen(true);}}}><UsersRound size={20} aria-hidden="true"/></button>{open&&<div className="family-member-selector-popup"><span className="family-member-selector-heading">Choose a workspace</span><div role="listbox" aria-label="Family members" id={id} ref={list} onKeyDown={keys}>{options.map(o=><button key={o.key} type="button" role="option" aria-selected={value===o.key} className="family-member-selector-option" onClick={()=>choose(o.key)}><span className={`family-member-selector-avatar ${o.type==='Non User'?'is-non-user':''}`} aria-hidden="true"><UserRound size={18}/></span><span className="family-member-selector-copy"><strong>{o.name}</strong><span><span className={`family-member-type ${o.type==='Non User'?'is-non-user':''}`}>{o.type}</span></span></span>{value===o.key&&<Check size={16} aria-hidden="true"/>}</button>)}</div>{!members.length&&<p className="family-member-selector-empty">No family members available.</p>}</div>}</div>;
}

function SharedFamilyTree({data,onEdit}){
 return <div className="family-units"><Surface className="family-hub"><SectionHeader title={`${data.owner.name}'s family circle`} description={data.readOnly===false?'Managed family information':'Shared family information · Read only'}/><div className="family-category-grid">{[{id:'bornIn',name:'Family Roots',description:'Parents and siblings',Icon:Sprout},{id:'formed',name:'Family Blossoms',description:'Partner and children',Icon:Flower2}].filter(category=>(data.contexts||data.people.map(person=>person.group)).includes(category.id)).map(({id,name,description,Icon})=>{
 const members=data.people.filter(p=>p.relationship==='Self'||p.group===id);
 const levels=[{id:'parents',label:'Parents',members:members.filter(p=>['Father','Mother','Parent'].includes(p.relationship))},{id:'peers',label:id==='bornIn'?`${data.owner.name} and siblings`:`${data.owner.name} and partner`,members:members.filter(p=>!['Father','Mother','Parent','Son','Daughter','Child'].includes(p.relationship))},{id:'children',label:'Children',members:members.filter(p=>['Son','Daughter','Child'].includes(p.relationship))}].filter(row=>row.members.length);
 return <section key={id} className={`family-category-section family-category-section-${id}`} aria-label={name}><div className={`family-category family-category-${id}`}><span className="family-category-icon"><Icon size={26} aria-hidden="true"/></span><span><strong>{name}</strong><span>{description}</span><small>{members.length} shared members</small></span></div><div className="family-circle-members family-tree">{levels.map((row,index)=><section className={`family-tree-level ${index?'family-tree-connected':''}`} key={row.id} aria-label={row.label}><h4 className="family-tree-level-label">{row.label}</h4><div className="family-tree-row">{row.members.map(person=>{const age=familyAge(person.birthDate);const tone=person.relationship==='Self'?'self':(['Father','Brother','Husband','Son'].includes(person.relationship)||person.gender==='male')?'male':(['Mother','Sister','Wife','Daughter'].includes(person.relationship)||person.gender==='female')?'female':'';return <article className={`family-circle-card ${tone?'family-circle-'+tone:''}`} key={person.id}><MemberPortrait name={person.name}/><div><h3>{person.name}</h3><p>{person.relationship}</p><span>{age===null?'Age not provided':`${age} ${age===1?'year':'years'} old`}</span></div>{onEdit&&person.relationship==='Self'?<IconButton icon={Pencil} label={`Edit ${person.name}'s family details`} onClick={()=>onEdit(person)}/>:<button className="family-readonly-options" type="button" disabled aria-label={`Member options unavailable for ${person.name}: read only`} title="Shared information is read only"><Ellipsis size={20} aria-hidden="true"/></button>}</article>;})}</div></section>)}{!members.length&&<p className="family-circle-empty">No members shared in this family.</p>}</div></section>;
 })}</div>{data.people.some(person=>person.relationship!=='Self'&&!person.group)&&<section className="family-shared-other"><SectionHeader title="Other family members" description="A relationship to the selected member has not been recorded."/><div className="family-tree-row">{data.people.filter(person=>person.relationship!=='Self'&&!person.group).map(person=><article className={`family-circle-card ${person.gender==='male'?'family-circle-male':person.gender==='female'?'family-circle-female':''}`} key={person.id}><MemberPortrait name={person.name}/><div><h3>{person.name}</h3><p>{person.relationship}</p><span>{familyAge(person.birthDate)===null?'Age not provided':`${familyAge(person.birthDate)} years old`}</span></div><button className="family-readonly-options" type="button" disabled aria-label="Relationship actions unavailable"><Ellipsis size={20} aria-hidden="true"/></button></article>)}</div></section>}{!(data.contexts||data.people.map(person=>person.group)).some(Boolean)&&!data.people.some(person=>person.relationship!=='Self')&&<p>No relationship branches are included in the shared information.</p>}</Surface></div>;
}
